Gemfile, Gemfile.lock, app/models/user.rb, db/migrate/20180529111454_add_columns_to_user.rb, db/schema.rb, db/seeds.rb
=> seeds, added colmuns missing to users

app/controllers/meals_controller.rb, app/views/meals/index.html.erb, app/views/meals/show.html.erb, app/views/pages/home.html.erb
@Sara-Foresti basic functions complete
=> basics-cmplete

Gemfile, Gemfile.lock, app/controllers/meals_controller.rb, app/javascript/packs/map.js, app/models/user.rb, app/views/layouts/application.html.erb, app/views/meals/index.html.erb, app/views/shared/_navbar.html.erb, config/initializers/geocoder.rb, db/migrate/20180529114215_add_coordinates_to_users.rb, db/migrate/20180529120815_add_address_to_users.rb, db/schema.rb, package.json, yarn.lock
@samricotta @Sara-Foresti @bilfar
=> Meal index

app/views/pages/dashboard.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
=> meals destroy action and dashboard implemented

app/controllers/meals_controller.rb, app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/meals/index.html.erb, config/initializers/geocoder.rb, config/routes.rb
Added gmaps package
added API keys, it works
Don't forget to run ```yarn install``` after pulling on master
=> added gmaps

app/controllers/meal_orders_controller.rb, app/controllers/meals_controller.rb, app/views/meals/_order_form.html.erb, app/views/meals/show.html.erb, app/views/orders/show.html.erb
=> meal_order controller and form on meal showpage

app/views/pages/dashboard.html.erb
@Sara-Foresti @ntlrfl @bilfar Half complete but i need to pull
=> nearly complete

app/views/pages/dashboard.html.erb
=> changes complete

Gemfile, Gemfile.lock, app/controllers/meals_controller.rb, app/models/meal.rb, app/uploaders/photo_uploader.rb, app/views/meals/_form.html.erb, app/views/meals/index.html.erb, app/views/meals/show.html.erb
=> added figari and cloudinary

app/controllers/meal_orders_controller.rb, app/controllers/orders_controller.rb, app/views/meals/show.html.erb, app/views/orders/_basket.html.erb, app/views/orders/_confirmation.html.erb, app/views/orders/show.html.erb, config/routes.rb, db/migrate/20180530133615_set_default_status_in_orders.rb, db/migrate/20180530134252_change_default_status_to_pending.rb, db/schema.rb
@Sara-Foresti @samricotta @bilfar
=> order show skeleton

app/controllers/meal_dietaries_controller.rb, app/controllers/meals_controller.rb, app/models/dietary.rb, app/models/meal.rb, app/models/meal_dietary.rb, app/views/meals/_form.html.erb, app/views/meals/index.html.erb, db/migrate/20180530153034_create_dietaries.rb, db/migrate/20180530153149_create_meal_dietaries.rb, db/migrate/20180530173342_remove_dietary_from_meals.rb, db/schema.rb, db/seeds.rb, test/controllers/meal_dietaries_controller_test.rb, test/models/dietary_test.rb, test/models/meal_dietary_test.rb
@samricotta 
please run migrations and seeds!
=> Search filters

app/views/pages/dashboard.html.erb
=> edit file completed

app/controllers/meal_orders_controller.rb, app/views/meals/_order_form.html.erb, app/views/meals/show.html.erb, app/views/orders/_basket.html.erb, db/seeds.rb
=> quantity-changed-when-meal-is-buyed

app/views/shared/_navbar.html.erb, db/schema.rb
=> adding button become a chef to homepage

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_index_meal.scss, app/views/meals/index.html.erb, app/views/pages/_top_chefs_home.html.erb
=> half complete

app/controllers/meals_controller.rb, app/views/meals/_form.html.erb, app/views/meals/_order_form.html.erb
=> added price to form

app/views/meals/show.html.erb, app/views/orders/_confirmation.html.erb, app/views/shared/_navbar.html.erb
=> add meal-review and added basket button in the navbar

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_index_meal.scss, app/views/meals/index.html.erb, app/views/meals/show.html.erb, app/views/pages/_six_recipes_home.html.erb, app/views/pages/_top_chefs_home.html.erb, app/views/shared/_banner.html.erb, app/views/shared/_small_card.html.erb
=> Home page cards

app/controllers/conversations_controller.rb, app/controllers/messages_controller.rb, app/controllers/pages_controller.rb, app/models/conversation.rb, app/models/message.rb, app/models/user.rb, app/views/conversations/index.html.erb, app/views/meals/show.html.erb, app/views/messages/index.html.erb, app/views/pages/dashboard.html.erb, config/routes.rb, db/migrate/20180605092211_create_conversations.rb, db/migrate/20180605092414_create_messages.rb, db/schema.rb, test/controllers/conversations_controller_test.rb, test/controllers/messages_controller_test.rb, test/models/conversation_test.rb, test/models/message_test.rb
@ntlrfl 
@Sara-Foresti 
@samricotta
=> add messages to user

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/helpers/application_helper.rb, app/javascript/packs/sign_in.js, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/meals/_form.html.erb, app/views/meals/edit.html.erb, app/views/meals/new.html.erb, app/views/meals/show.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_sign_in_modal.html.erb
=> Forms style

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_messages.scss, app/controllers/conversations_controller.rb, app/controllers/pages_controller.rb, app/views/meals/show.html.erb, app/views/messages/index.html.erb, app/views/pages/_messages_page.html.erb, app/views/pages/dashboard.html.erb
=> Frontend messages

app/assets/stylesheets/config/_fonts.scss
=> changed font

app/views/meals/show.html.erb
=> portions detail on show page sorted

app/controllers/meals_controller.rb, app/views/meals/_form.html.erb, app/views/meals/_order_form.html.erb, app/views/meals/show.html.erb, db/migrate/20180606161255_add_ready_to_meals.rb, db/schema.rb
@ntlrfl @bilfar @samricotta 
Please, run migrations once you pull
=> ready time and date added and bugs fixed

public/404.html, public/500.html
=> 404 and 500 classes changed
